# Generated by Django 4.1.7 on 2023-03-11 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(error_messages={'unique': 'Empresa já cadastrada ! ! !'}, max_length=150, unique=True, verbose_name='Nome')),
                ('email', models.EmailField(error_messages={'unique': 'Email já cadastrado ! ! !'}, max_length=254, unique=True, verbose_name='Email')),
                ('fone', models.CharField(max_length=20, verbose_name='Fone')),
                ('cnpj', models.CharField(error_messages={'unique': 'CNPJ já cadastrado ! ! !'}, max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('Pais', models.CharField(max_length=100, verbose_name='País')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hospedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('fone', models.CharField(blank=True, max_length=25, verbose_name='Fone')),
                ('profissao', models.CharField(blank=True, max_length=100, verbose_name='Profissão/Ocupação')),
                ('nacionalidade', models.CharField(blank=True, max_length=100, verbose_name='Nacionalidade')),
                ('datanascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('generohospede', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10, verbose_name='Gênero')),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('tipodocindentificacao', models.CharField(blank=True, choices=[('Carteira de indentidade', 'Carteira de indentidade'), ('Carteira de ind. Estrangeira', 'Carteira de ind. Estrangeira'), ('Passaporte', 'Passaporte'), ('Certidção de Nascimento', 'Certidção de Nascimento')], max_length=50, verbose_name='Documento de indentificação')),
                ('numerodocumento', models.CharField(blank=True, max_length=50, verbose_name='Número documento')),
                ('orgaodocumento', models.CharField(blank=True, max_length=50, verbose_name='Orgão documento')),
                ('endereco', models.CharField(blank=True, max_length=100, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('Pais', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('motviagemLazerferias', models.BooleanField(blank=True, default=False)),
                ('motviagemCongressoFeira', models.BooleanField(default=False)),
                ('motviagemEstudoCursos', models.BooleanField(default=False)),
                ('motviagemNegocios', models.BooleanField(default=False)),
                ('motviagemParentesAmigos', models.BooleanField(default=False)),
                ('motviagemReligiao', models.BooleanField(default=False)),
                ('motviagemCompras', models.BooleanField(default=False)),
                ('motviagemOutros', models.BooleanField(default=False)),
                ('meiotransporteAviao', models.BooleanField(default=False)),
                ('meiotransporteCarro', models.BooleanField(default=False)),
                ('meiotransporteOnibus', models.BooleanField(default=False)),
                ('meiotransporteMoto', models.BooleanField(default=False)),
                ('meiotransporteNavio', models.BooleanField(default=False)),
                ('meiotransporteTrem', models.BooleanField(default=False)),
                ('meiotransporteOutros', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.empresa')),
            ],
        ),
    ]
