# Generated by Django 4.1.7 on 2023-03-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamentos',
            name='qtdpessoas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº. Pessoas'),
        ),
        migrations.AddField(
            model_name='apartamentos',
            name='valorporexcedente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor por excedente'),
        ),
    ]
