# Generated by Django 4.1.7 on 2023-03-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_apartamentos_qtdpessoas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamentos',
            name='qtdpessoas',
            field=models.IntegerField(verbose_name='Nº. Pessoas'),
        ),
        migrations.AlterField(
            model_name='apartamentos',
            name='valorporexcedente',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por excedente'),
        ),
    ]
