# Generated by Django 4.1.7 on 2023-03-18 02:43

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_hospedes_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedes',
            name='cpf',
            field=cpf_field.models.CPFField(blank=True, max_length=14, validators=[home.models.validar_cpf], verbose_name='cpf'),
        ),
        migrations.CreateModel(
            name='apartamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=50, verbose_name='Descrição')),
                ('tipoapart', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50, verbose_name='Tipo')),
                ('ramal', models.CharField(blank=True, max_length=10, verbose_name='Ramal')),
                ('valordiaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=100, verbose_name='Nacionalidade')),
                ('empresa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.empresa')),
            ],
        ),
    ]
