# Generated by Django 4.1.7 on 2023-03-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_hospedes_cpf_apartamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamentos',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='apartamentos',
            name='tipoapart',
            field=models.CharField(blank=True, choices=[('Simples', 'Simples'), ('Stander', 'Stander'), ('Luxo', 'Luxo'), ('Super Luxo', 'Super Luxo'), ('Duplex', 'Duplex'), ('Cobertura', 'Cobertura'), ('Loft', 'Loft'), ('Rústico', 'Rústico')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='apartamentos',
            name='valordiaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
