# Generated by Django 4.1.7 on 2023-03-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_apartamentos_tipostatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensconsumo',
            name='margemLucro',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Margem %'),
        ),
    ]
