# Generated by Django 4.1.7 on 2023-03-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_apartamentos_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamentos',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Observação'),
        ),
    ]
