# Generated by Django 4.1.7 on 2023-03-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_apartamentos_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamentos',
            name='valordiaria',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da diária'),
        ),
    ]
