# Generated by Django 4.1.7 on 2023-03-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_movimentosaparts_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentosaparts',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de crédito'), ('cartao_debito', 'Cartão de débito'), ('transferencia_bancaria', 'Transferência bancária'), ('boleto_bancario', 'Boleto bancário'), ('cheque', 'Cheque'), ('paypal', 'PayPal'), ('cartao_refeicao', 'Cartão Refeição'), ('deposito', 'Depósito em conta'), ('credito_consumo', 'Crédito de Consumo'), ('voucher', 'Voucher'), ('outro', 'Outro')], max_length=25, null=True, verbose_name='Forma Pgto.'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='pago_sn',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='qtd_excedentes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Excedentes'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='valor_adiantamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Adiantamento'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='valor_consumo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor consumo'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='valor_desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Desconto'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='valor_pago_excedente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor por excedentes'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='valor_total_conta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='valor_total_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Líquido'),
        ),
    ]
