# Generated by Django 4.1.7 on 2023-03-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_itensconsumoaparts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensconsumoaparts',
            name='apartamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.apartamentos'),
        ),
        migrations.AlterField(
            model_name='itensconsumoaparts',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.empresa'),
        ),
        migrations.AlterField(
            model_name='itensconsumoaparts',
            name='hospede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.hospedes'),
        ),
        migrations.AlterField(
            model_name='itensconsumoaparts',
            name='movimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.movimentosaparts'),
        ),
        migrations.CreateModel(
            name='MovimentoReservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_hospedes', models.IntegerField(verbose_name='Nº. hóspedes')),
                ('data_reserva', models.DateField(blank=True, null=True, verbose_name='Data da reserva')),
                ('data_confirmacao', models.DateField(blank=True, null=True, verbose_name='Data da confirmação')),
                ('entrada_prevista', models.DateField(blank=True, null=True, verbose_name='Entrada prevista')),
                ('saida_prevista', models.DateField(blank=True, null=True, verbose_name='Saída prevista')),
                ('entrada_efetivada', models.DateField(blank=True, null=True, verbose_name='Entrada efetivada')),
                ('valor_da_reserva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da reserva')),
                ('valor_antecipado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Antecipação')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('status_reserva', models.CharField(blank=True, choices=[('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Pendente', 'Pendente')], max_length=15, null=True, verbose_name='Status Reserva')),
                ('apartamento', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.apartamentos')),
                ('empresa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.empresa')),
                ('hospede', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.hospedes')),
            ],
        ),
    ]
