# Generated by Django 4.1.7 on 2023-03-30 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_itensconsumoaparts_apartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensconsumoaparts',
            name='item_lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.itensconsumo'),
        ),
    ]
