# Generated by Django 4.1.7 on 2023-03-31 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_itensconsumoaparts_item_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensconsumoaparts',
            name='item_lancamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.itensconsumo'),
        ),
        migrations.AlterField(
            model_name='itensconsumoaparts',
            name='qtd_lancamento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qtd.'),
        ),
    ]
