# Generated by Django 4.1.7 on 2023-04-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_itensconsumoaparts_item_lancamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoreservas',
            name='apartamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.apartamentos'),
        ),
        migrations.AlterField(
            model_name='movimentoreservas',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.empresa'),
        ),
        migrations.AlterField(
            model_name='movimentoreservas',
            name='hospede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.hospedes'),
        ),
        migrations.AlterField(
            model_name='movimentoreservas',
            name='qtd_hospedes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº. hóspedes'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='apartamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.apartamentos'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.empresa'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='hospede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.hospedes'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='qtd_hospedes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº. hóspedes'),
        ),
    ]
