# Generated by Django 4.1.7 on 2023-04-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_movimentoreservas_apartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentosaparts',
            name='valor_adiantamento',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor Adiantamento'),
        ),
    ]
