# Generated by Django 4.1.7 on 2023-04-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_movimentosaparts_valor_adiantamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentosaparts',
            name='valor_adiantamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Adiantamento'),
        ),
    ]
