# Generated by Django 4.1.7 on 2023-04-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_movimentosaparts_valor_adiantamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamentos',
            name='valordiaria',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da diária'),
        ),
        migrations.AlterField(
            model_name='apartamentos',
            name='valorporexcedente',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor por excedente'),
        ),
        migrations.AlterField(
            model_name='itensconsumo',
            name='estoqueAtual',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Estoque Atual'),
        ),
        migrations.AlterField(
            model_name='itensconsumo',
            name='estoqueMinimo',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Estoque Mínimo'),
        ),
        migrations.AlterField(
            model_name='itensconsumo',
            name='margemLucro',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Margem %'),
        ),
        migrations.AlterField(
            model_name='itensconsumo',
            name='precoCompra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Preço Compra'),
        ),
        migrations.AlterField(
            model_name='itensconsumo',
            name='precoVenda',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço Venda'),
        ),
        migrations.AlterField(
            model_name='itensconsumoaparts',
            name='preco_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='itensconsumoaparts',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='movimentoreservas',
            name='valor_antecipado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Antecipação'),
        ),
        migrations.AlterField(
            model_name='movimentoreservas',
            name='valor_da_reserva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor da reserva'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='valor_consumo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor consumo'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='valor_desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Desconto'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='valor_pago_excedente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor por excedentes'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='valor_total_conta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='movimentosaparts',
            name='valor_total_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Líquido'),
        ),
    ]
